### PR TITLE
flupe's vim8 terminal support - rebased onto master

### PR DESCRIPTION
**Pull request by mitchmindtree**
This rebases @flupe's work on implementing Vim 8 terminal support (#42) onto master. 

Also removes mention of the not-yet-implemented `:TidalStart` command. I'll open separate issues for these.

---

I'm not yet savvy enough with VimL to review the rest of the changes here properly just yet, and I'm yet to actually test them locally :smiling_face_with_tear:  Will report back once I get the chance.

@munshkr are you happy to remove `tmux` tiling support altogether in favour of native terminal support? I think it does make a lot of sense to encourage vim's native terminal instead as it skips the need for one extra 3rd party tool. I think it also avoids issues related to opening tmux inside of another instance of tmux (I'm almost always already inside a tmux pane :smile: ). Perhaps we can provide some handy tmux scripts/config under a separate tidalcycles repo?

### CODE REVIEW

**Comment by munshkr** [comment]
Hi @mitchmindtree thank for you reviving this! I think it makes a lot of sense to make the terminal mode the default and leave tmux as optional, for the reasons you mention. I wouldn't remove it completely, but it should definitely be optional, and we could provide instructions on how to enable it.
 
I'll review it and come back later today.

**Review by mitchmindtree — COMMENTED** [review]
@munshkr In the hopes of making this PR a little easier to review, I've removed most of the unrelated / unnecessary formatting changes from the original PR, as well as some of the tmux-related code removal after your comment mentioning you'd like to keep support for it.

I've also added a few inline comments with my interpretation on some of these changes.

Fwiw, I'm using this currently with Vim8 (via [my new tidalcycles.nix flake](https://github.com/mitchmindtree/tidalcycles.nix)) and all appears to be working nicely :+1: 

Let me know if there's anything else I can do to help land this!

**Comment by mitchmindtree** [comment]
I have a follow-up commit [here](https://github.com/mitchmindtree/vim-tidal/pull/1) based on these changes that allows for specifying a custom `BootTidal.hs` path via `g:boot_tidal`, but I'll leave it for a follow-up PR to keep this one as small as possible.

**Comment by mitchmindtree** [comment]
Hey there @munshkr, would you be interested in some help with maintaining the plugin? I'd be happy to assist :bow:

**Comment by mitchmindtree** [comment]
Thanks again for adding me as a collaborator @munshkr :pray: Going to land this and start opening some new PRs for some pending work I have downstream.

**Pull request merged**
